# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_migrate', '0002_auto_20160222_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsschema',
            name='joels_fave_field',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
